using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using JackScottAU.BrainFuck.Library.Types;

namespace JackScottAU.BrainFuck.Library
{
    public class CCompiler
    {
        public StringBuilder Compile(List<IInstruction> syntaxTree)
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("/*\n\tThis program generated by Fred (A Portable BrainFuck-to-C Converter):\n");
            builder.AppendLine("\t  http://www.fooproject.com.au/open-source/fred\n*/\n\n");

            builder.AppendLine("#include <stdio.h>\n\n");
            builder.AppendLine("int main() {\n");
            builder.AppendLine("\tchar Array["+30001+"];\n");
            builder.AppendLine("\tunsigned int Pointer = 0;\n");
            builder.AppendLine("\twhile(Pointer<="+30000+") {\n");
            builder.AppendLine("\t\tArray[Pointer]=0;\n");
            builder.AppendLine("\t\tPointer++;\n");
            builder.AppendLine("\t};\n");
            builder.AppendLine("\tPointer = 0;\n\n");
            builder.AppendLine("\t/* START OF BRAINFUCK COMMANDS */\n");

            //TODO

            builder.AppendLine("\t/* END OF BRAINFUCK COMMANDS */\n");
            builder.AppendLine("};\n/* END OF FILE*/\n\n");

            return builder;
        }
    }
}
